Update codebase to python 3
ReddyLab/ggr-cwl-ipynb-gen pull request #15
Opened 2021-03-15 16:35 UTC by alexbarrera

This `dev` branch addresses a couple things needed moving forward:
- Migrate code to Python 3 (worth noting that the new code will not be compatible with Python 2.x anymore)
- Add `setup.py` and some other necessary file for packaging the tool and make it installable with `pip install /path/to/ggr-cwl-ipynb-gen`

Since we don't have unittests or CI yet, it might be one for one of the reviewers to download and test before merging (if you haven't yet)

2021-03-15 19:25 UTC, tncowart requested changes
In addition to my comments I don't think you should check in the symlinks.

2021-03-15 19:25 UTC, tncowart commented on requirements.txt
> +pymongo
Shouldn't pymongo be versioned too?

2021-03-15 19:25 UTC, tncowart commented on requirements.txt
> +setuptools
I don't think you need setup tools here because it's mentioned in pyproject.toml

2021-03-15 19:25 UTC, tncowart commented on MANIFEST.in
> +include templates/*
I don't think you need a manifest file because you use `data_files` in setup.py

2021-03-15 21:23 UTC, alexbarrera commented on requirements.txt
> +pymongo
I didn't versioned pymongo because I'm not sure where to draw the line of the oldest version that should be accepted

2021-03-15 21:25 UTC, alexbarrera commented
What's the argument to remove the `symlinks`? I wanted to keep them for backwards compatibility, although admittedly this should be work with Python 2.x, so perhaps I shouldn't worry... Curious about the justification to remove them though

2021-03-15 21:32 UTC, tncowart commented on requirements.txt
> +pymongo
Your initial commit was 4/26/2017 and it looks like the newest version of pymongo at the time was 3.4.0, so probably that version (it's only at 3.11 now, 4 years later).

2021-03-15 21:37 UTC, tncowart commented
Just to declutter the repo. I don't feel super strongly about it though.

2021-03-15 21:43 UTC, alexbarrera commented
Got it, yeah, I imagined that was it. I also feel like symlinks are prob something that can stay away from the repo, not common to find them committed.

Thanks for all the comments!!

2021-03-15 21:45 UTC, tncowart approved these changes

2021-03-15 21:48 UTC, merged

2021-03-23 13:21 UTC, tncowart commented
Closes #11